### ISSUE TITLE
Base class construction in Wren script leaks destructor calls from derived class

### ISSUE THREAD

**Issue by germandiagogomez** [matusnovak/wrenbind17#13]
Hello everyone. 

I found an issue which seems to be a bug, not sure if it is wrenbind-specific or it is just wren.

The bug is the following. Given this:

```
// C++
class Base {
 public:
   virtual ~Base();

   static std::shared_ptr<Base> factory();
};

class Derived {
public:
   virtual ~Derived() { ... }
};

std::shared_ptr<Base> Base::factory() { return std::make_shared<Derived>(); }

// Wren code
_myInstanceVar = Base.factory();
```

Since `_myInstanceVar` holds a `Derived` but returns a `Base`, it seems that Wren does *not* call the destructor for `Derived` at all.

This seems to be unexpected I think and it was causing a crash in my own code.

**Comment by matusnovak** [comment]
There seems to be a bug. Thank you for spotting it.

The destructor (in Wren's terms a `finalize` allocator) is not called unless some `.ctor<>()` is added to the class.

Fixed by always adding `finalize` to the Wren allocator (commit here: https://github.com/matusnovak/wrenbind17/commit/a864db3f58a672295d2ae5a67f5437f58f455666)

Also added a unit test to verify that it works as it should, based on your example (commit here: https://github.com/matusnovak/wrenbind17/commit/4ae1512bbc7b7ce89e50f7979471a1076643b798)

It should be fixed now. Let me know if the latest master works for you.

I believe always adding finalize to all classes should be fine. Even if the class, for any reason, has a non-public destructor, passing it as a raw pointer to Wren would wrap it in a shared_ptr with no destructor. The shared_ptr would be destructed, not the instance behind the pointer itself.

**Comment by germandiagogomez** [comment]
Thanks for the fast reply and for the commit. 

A doubt remains:

- Do I need to add a ctor<> still? I just use a factory and try to not expose any ctor from derived classes in Wren.

**Comment by germandiagogomez** [comment]
I can confirm it is working correctly on my side.

**Comment by matusnovak** [comment]
Awesome. Thank you for letting me know.
